<a href="https://colab.research.google.com/github/riz1raj/CVPR/blob/master/04_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3]) #rank 1 array
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

a[2] = 5
a


<class 'numpy.ndarray'>
(3,)
1 2 3


array([1, 2, 5])

In [ ]:
b = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]

              ])  #creating a rank 2 array
print(type(b))
print(b.shape)
print(b[2][1])

<class 'numpy.ndarray'>
(3, 3)
8


In [ ]:
arr_zero = np.zeros((3,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_zero = np.ones((3,3))
print(arr_zero)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr_constant = np.full((3,3),4)
print(arr_constant)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
arr_iden = np.eye(5)
print(arr_iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr_rand = np.random.random((5,5))
print(arr_rand)

[[0.80983538 0.12600134 0.83236146 0.17393047 0.86550958]
 [0.56204735 0.79678904 0.24439967 0.63981591 0.97860937]
 [0.28929105 0.59642912 0.64289818 0.53500005 0.38363982]
 [0.91785572 0.17083884 0.51051845 0.5234242  0.80636721]
 [0.89802233 0.4680244  0.08911166 0.92110051 0.20477199]]


In [ ]:
# array indexing

a = np.array([
              
              [1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]
              
              ])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:

a[0:4:2]

array([[ 6,  2,  3],
       [12,  8,  9]])

In [ ]:
b = a[1:3, 2:4]
print(b)
print(b[0][1])

[[ 8  9]
 [13 14]]
9


In [ ]:
b[0][0] = 99
print(b)


[[99  9]
 [13 14]]


In [ ]:
a = np.array([
              [1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]
            ])

row1 =  a[1,:] #creating a rank 1 array
row2 = a[1:2, :]
print(row1, row1.shape)
print(row2, row2.shape)

col1 = a[:,1]
col2 = a[:,1:2]
print(col1,col1.shape)
print(col2,col2.shape)

[ 6  7  8  9 10] (5,)
[[ 6  7  8  9 10]] (1, 5)
[ 2  7 12] (3,)
[[ 2]
 [ 7]
 [12]] (3, 1)


In [ ]:
a = np.array([
              [1,2],
              [3,4],
              [5,6]
])
print(a)
print(a[[0,1,2],[0,1,0]]) #shape (3,)

print([a[0][0], a[1][1], a[2][0]])

print(a[0,0], [1,1])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1, 4, 5]
1 [1, 1]


In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b= np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [ ]:
print(np.arange(4))
print(a[np.arange(4), b])

[0 1 2 3]
[ 1  6  7 11]


In [ ]:
a[np.arange(4),b] +=5
print(a)

[[ 6  2  3]
 [ 4  5 11]
 [12  8  9]
 [10 16 12]]
