<a href="https://colab.research.google.com/github/riz1raj/CVPR/blob/master/numpy_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Boolean numpy array
import numpy as np

arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
              ])
bool_index = arr>2
print(bool_index)
print(arr[bool_index])
print(arr[arr>2])

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


In [2]:
#data type in numpy

a= np.array([1,2,3])
print(a.dtype)

b= np.array([1,2,3.3])
print(b.dtype)

c= np.array([1,2,3,4,5.5], dtype=np.int64)
print(c.dtype)

int64
float64
int64


In [3]:
x = np.array([
              [1,2,3],
              [4,5,6]
              ], dtype =np.float64)
y= np.array([
             [7,8,9],
             [1,2,3]
            ], dtype= np.float64)
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))


[[ 8. 10. 12.]
 [ 5.  7.  9.]]
[[ 8. 10. 12.]
 [ 5.  7.  9.]]
[[-6. -6. -6.]
 [ 3.  3.  3.]]
[[-6. -6. -6.]
 [ 3.  3.  3.]]
[[ 7. 16. 27.]
 [ 4. 10. 18.]]
[[ 7. 16. 27.]
 [ 4. 10. 18.]]
[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]
[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [4]:
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

a= np.array([2,3])
b= np.array([4,5])

print(a.dot(b))     #inner product of vectors
print(np.dot(a,b))

print(x.dot(a))  #matrix / vector will produce rank 1 array
print(np.dot(x,a))
print(x.dot(y))  #matrix / vector will produce rank 1 array
print(np.dot(x,y))

23
23
[ 8 18]
[ 8 18]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [5]:
x= np.array([[1,2],[3,4]])

print(np.sum(x, axis=None))  #sum of all elements
print(np.sum(x, axis=0)) #sum of each column
print(np.sum(x, axis=1)) #sum of each row


10
[4 6]
[3 7]


In [6]:
print(x.T)  #transpose the matrix
a = np.array([1,2,3,4])
print(a.T)  #rank 1 matrix doesnt trnaspose


[[1 3]
 [2 4]]
[1 2 3 4]


In [7]:
#broadcasting

a= np.array([
             [1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]
             ])
b= np.array([1,2,3])
c= np.empty_like(a)
print(c)


for i in range(4):
  c[i,:] = a[i,:] +b
  print(c)


[[       68193568               0            1601]
 [       41627328 139946944968640 139946944968640]
 [139946944968640 139946944968640               0]
 [              4      4294967296               9]]
[[              2               4               6]
 [       41627328 139946944968640 139946944968640]
 [139946944968640 139946944968640               0]
 [              4      4294967296               9]]
[[              2               4               6]
 [              5               7               9]
 [139946944968640 139946944968640               0]
 [              4      4294967296               9]]
[[         2          4          6]
 [         5          7          9]
 [         8         10         12]
 [         4 4294967296          9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [8]:
ab = np.tile(b,(4,1)) #stack 4 copies of b on top each other
print(ab)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
test = a+ab
print(test)

print(a)
print(b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]


In [10]:
a= np.array([1,2,3])     #shape(3,)
b= np.array([1,2])       #shape(2,)

print(np.reshape(a,(3,1))*b)

x= np.array([[1,2,3],[4,5,6]])
print(a.shape, x.shape)
print(x+a)

print(x.T + b)
print((x.T + b).T)


[[1 2]
 [2 4]
 [3 6]]
(3,) (2, 3)
[[2 4 6]
 [5 7 9]]
[[2 6]
 [3 7]
 [4 8]]
[[2 3 4]
 [6 7 8]]
